### ISSUE TITLE
Error on Bollinger and Ichimoku

### ISSUE THREAD

**Issue by t3ch9** [carlfarterson/TAcharts#13]
Hi, after the recent update 0.0.29, getting the following error when running bollinger and ichimoku from the README example:

Traceback (most recent call last):
  File "test.py", line 21, in <module>
    i.build(20, 60, 120, 30)
  File "C:\Users\admin\Documents\PYTHON\Coin\TAcharts\TAcharts\indicators\ichimoku.py", line 90, in build
    self._build_lines(tenkan=tenkan_interval, kijun=kijun_interval)
  File "C:\Users\admin\Documents\PYTHON\Coin\TAcharts\TAcharts\indicators\ichimoku.py", line 58, in _build_lines
    high = sma(self.df["high"], val, "max")
  File "C:\Users\admin\Documents\PYTHON\Coin\TAcharts\TAcharts\wrappers.py", line 33, in wrapper
    args = tuple(x if type(x) != pd.Series else args[0].to_numpy(na_value=0) for x in args)
  File "C:\Users\admin\Documents\PYTHON\Coin\TAcharts\TAcharts\wrappers.py", line 33, in <genexpr>
    args = tuple(x if type(x) != pd.Series else args[0].to_numpy(na_value=0) for x in args)
TypeError: to_numpy() got an unexpected keyword argument 'na_value'

**Comment by ChiragChhatbar** [comment]
The above issue for me got fixed by updating pandas to 1.2.3

However, there is still another issue for me
`ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`
