### ISSUE TITLE
renko got builtins.TypeError during current data fetch from ticks

### ISSUE THREAD

**Issue by gaju432** [carlfarterson/TAcharts#4]
R/Sir,
i try to find renko chart or data for making indicator in zerodha api python ticks
df is same as your data df
from TAcharts.indicators.renko import Renko

r = Renko(df)
r.set_brick_size(auto=True, atr_period=2)
r.build()

r.plot()

Unhandled Error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\twisted\websocket.py", line 288, in dataReceived
    self._dataReceived(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\websocket\protocol.py", line 1206, in _dataReceived
    self.consumeData()
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\websocket\protocol.py", line 1218, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\websocket\protocol.py", line 1578, in processData
    fr = self.onFrameEnd()
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\websocket\protocol.py", line 1700, in onFrameEnd
    self._onMessageEnd()
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\twisted\websocket.py", line 316, in _onMessageEnd
    self.onMessageEnd()
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\websocket\protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autobahn\twisted\websocket.py", line 319, in _onMessage
    self.onMessage(payload, isBinary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\kiteconnect\ticker.py", line 71, in onMessage
    self.factory.on_message(self, payload, is_binary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\kiteconnect\ticker.py", line 670, in _on_message
    self.on_ticks(self, self._parse_binary(payload))
  File "E:\crsitry\ta\tachartsrenko.py", line 157, in on_ticks
    r.set_brick_size(auto=True, atr_period=2)
builtins.TypeError: set_brick_size() got an unexpected keyword argument 'atr_period'

i  m solanki from raj. 8104093607

**Comment by pegahcarter** [comment]
This is the same error as the other one, instead of passing in `atr_period=2` you should be passing in `atr_interval=2`.  Will update documentation :)

**Comment by pegahcarter** [comment]
https://github.com/carlfarterson/TAcharts/commit/8f4e00fd2bcd03300bdef39170a7faf9b65c9458
