### ISSUE TITLE
FileNotFoundError when instanciating OHLCV

### ISSUE THREAD

**Issue by Iltotore** [carlfarterson/TAcharts#7]
Hello,
I'm trying to use the README example:
```python
# NOTE: we are using 1-hour BTC OHLCV data from 2019.01.01 00:00:00 to 2019.12.31 23:00:00
from TAcharts.utils.ohlcv import OHLCV

df = OHLCV().btc

df.head()
```

But I get an error when initializing OHLCV:

```
Traceback (most recent call last):
  File "C:/Users/rapha/PycharmProjects/forex/main.py", line 4, in <module>
    data_frame = OHLCV()
  File "C:\Users\rapha\AppData\Roaming\Python\Python38\site-packages\TAcharts\utils\ohlcv.py", line 21, in __init__
    self.fetch_OHLCV()
  File "C:\Users\rapha\AppData\Roaming\Python\Python38\site-packages\TAcharts\utils\ohlcv.py", line 30, in fetch_OHLCV
    os.mkdir(self.basepath)
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'C:\\Users\\rapha\\AppData\\Roaming\\Python\\Python38\\site-packages\\TAcharts/ohlcv'
```

Is it a bug or did I miss something ?

**Comment by pegahcarter** [comment]
Hey!  Yeah, you found the missing bug I haven't gotten around to patching... Now that it's officially an issue, I'll get it fixed and follow up :+1:

**Comment by pegahcarter** [comment]
Done :ok_hand:

https://github.com/carlfarterson/TAcharts/commit/a8e13a59f300cb02bc2ad1dc99a956e15691fef1

**Comment by pegahcarter** [comment]
@Iltotore It should work now, try `pip uninstall TAcharts` then `pip install TAcharts`

**Comment by Iltotore** [comment]
Ok, thank you.
