### ISSUE TITLE
Error in Ichimoku from README example

### ISSUE THREAD

**Issue by t3ch9** [carlfarterson/TAcharts#9]
Hello,
I'm trying to use the README example:

Ichimoku

```
from TAcharts.indicators.ichimoku import Ichimoku

i = Ichimoku(df)
i.build(20, 60, 120, 30)

i.plot()
```
Getting the following error:

Traceback (most recent call last):
  File "test1.py", line 21, in <module>
    i.build(20, 60, 120, 30)
  File "C:\Users\admin\Documents\PYTHON\Coin\TAcharts\indicators\ichimoku.py", line 90, in build
    self._build_lines(tenkan=tenkan_interval, kijun=kijun_interval)
  File "C:\Users\admin\Documents\PYTHON\Coin\TAcharts\indicators\ichimoku.py", line 58, in _build_lines
    high = sma(self.df["high"], val, "max")
  File "C:\Users\admin\Documents\PYTHON\Coin\TAcharts\wrappers.py", line 29, in wrapper
    return fn(*args, **kwargs)
TypeError: sma() takes from 1 to 2 positional arguments but 3 were given

**Comment by pegahcarter** [comment]
https://github.com/carlfarterson/TAcharts/pull/11
